name: 'Deployment Workflow'

on: [push]

jobs:

  environment-job:
    name: 'Environment'
    runs-on: 'ubuntu-latest'

    outputs:
      TEST: 'true'

    steps:
      - name: 'Environment Test'
        run: date;

  build-job:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    needs: 'environment-job'
    if: ${{ needs.environment-job.outputs.TEST != 'true' }}

    steps:
      - name: 'Build Test'
        id: 'build-test'
        run: date;

  deploy-job:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    needs: 'build-job'

    if: |
      always() &&
      (needs.build-job.result == 'success' || needs.build-job.result == 'skipped')

    steps:
      - name: 'Deploy Test'
        id: 'deploy-test'

        run: date;
