name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions-1:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: fake folder
        run: |
          mkdir ./dist
          echo 111 >> ./dist/111.txt          
      - uses: actions/cache/save@v3
        with:
          path: ./dist
          key: dist-${{ github.sha }}
          enableCrossOsArchive: true

  Explore-Gitea-Actions-2:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: ./dist
          key: dist-${{ github.sha }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
