name: test

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - prod

env:
  name_dev: scott
  name_prod: tiger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: output test
        run: |
          echo ${{ github.event.inputs.env }}
          echo ${{ env[format('name_{0}', github.event.inputs.env)] }}
